-- schema.sql
CREATE DATABASE IF NOT EXISTS reservation-salle
CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE reservation-salle;

CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    lastname VARCHAR(100) NOT NULL,
    firstname VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    INDEX idx_email (email)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS reservation (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    object VARCHAR(255) NOT NULL,
    date TIMESTAMP,
    hour_start INT,
    hour_end INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB;